### ISSUE TITLE
Update script to support "Call" signature type

### ISSUE THREAD

**Issue by Makar8000** [gamous/FFXIVNetworkOpcodes#6]
In [this](https://github.com/gamous/FFXIVNetworkOpcodes/commit/b84754a215cb4a4a2efc987376eef7017533a4ce#diff-cf99987eef1dc0e77282b3868dc250758f0ab777df8877e482683b76cad85bb9R15-R18) change, a new structure for signatures was introduced for Global `ProcessSystemLogMessage` . However, it seems the [code](https://github.com/gamous/FFXIVNetworkOpcodes/blob/82646e96e5fb37112ebc379f8f209ecd490f5da2/ffxiv_opcode_finder.py#L293-L295) was not updated to support this, causing a TypeError exception to be thrown

```D:\IDA Plugins\opcode-finder\ffxiv_opcode_finder.py: in method 'get_func', argument 1 of type 'ea_t'
Traceback (most recent call last):
  File "D:\IDA 7.7\python\3\ida_idaapi.py", line 580, in IDAPython_ExecScript
    exec(code, g)
  File "D:/IDA Plugins/opcode-finder/ffxiv_opcode_finder.py", line 449, in <module>
    serverzone = ServerZoneIpcType(config)
  File "D:/IDA Plugins/opcode-finder/ffxiv_opcode_finder.py", line 299, in __init__
    self.funcs[func] = SimpleSwitch(self.config["__init__"][func])
  File "D:/IDA Plugins/opcode-finder/ffxiv_opcode_finder.py", line 162, in __init__
    self.switch_func = idaapi.get_func(switch_address)
  File "D:\IDA 7.7\python\3\ida_idaapi.py", line 735, in get_func
    return _ida_funcs.get_func(*args)
TypeError: in method 'get_func', argument 1 of type 'ea_t'
```
Note: line numbers in the above will be incorrect due to local changes

**Comment by gamous** [comment]
Supported at [commit(2fe3a4)](https://github.com/gamous/FFXIVNetworkOpcodes/commit/2fe3a4730cf0e581aaf593fa36f4b0b57d10f5f8)
